### ISSUE TITLE
implement jwt token refresh

### ISSUE THREAD

**Issue by tsearle** [openline-ai/openline-agent-platform-api#9]
currently if the agent app is open for a while, it stops working because the jwt has expired.

the agent app should get the expire time from the jwt and use the refresh token to get a new jwt before the expiration happens

**Comment by tsearle** [comment]
after talking to @edifirut it seems the best place to implement this is inside the JWTTokenFilter

**Comment by tsearle** [comment]
I tried modifying JWTTokenFilter to refresh the token upon detecting the previous token has expired.  The jwt refresh got rejected with a 400 which indicated the token has either been expired or revoked.

So now I think refreshing the token is something that has to be done BEFORE the jwt expires.  Perhaps as a timer task called from the browser?

**Comment by tsearle** [comment]
another note, refresh tokens are currently disabled by default in the current fusion auth docker compose image (we may want to update the sql there to enable it)

To enable it go here:
http://localhost:9011/admin/application/edit?applicationId=5ddba7cf-6486-4ada-8051-22b55dbf21c9&tenantId=97e0a537-726d-44aa-9f8c-e2d26700a8ec

then go to the security table and enable jwt refresh tokens.

I also notice though I enabled refresh tokens, jwt refresh was disabled.  That perhaps was my issue the entire time (*facepalm*)

**Comment by edifirut** [comment]
@tsearle i think we need to stop working on this. we are going to move the token generation/refresh under the Apache APISix gateway
